# Generated by Django 4.2.13 on 2024-06-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shtraf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shtraf',
            old_name='name',
            new_name='user',
        ),
    ]
