# Generated by Django 4.2.13 on 2024-06-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shtraf', '0002_rename_name_shtraf_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shtraf',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.CreateModel(
            name='Spisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(verbose_name='Сумма штрафа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата наложения штрафа')),
                ('reason', models.CharField(default='Нет комментария', max_length=255, verbose_name='Причина: ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
            },
        ),
    ]
