# Generated by Django 4.2.13 on 2024-06-14 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shtraf', '0003_alter_shtraf_options_spisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='spisanie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
