# Generated by Django 4.2.13 on 2024-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otdel',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ДПС'),
        ),
    ]
