# Generated by Django 4.2.13 on 2024-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otdel_options_alter_customusers_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_leed',
            field=models.BooleanField(default=False, verbose_name='Teamleed'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администрация'),
        ),
    ]
